AntiFeatures:
  NonFreeNet:
    en-US: Relies on Trenitalia's ViaggiaTreno service and, for Italo trains, on an
      unofficial Italo endpoint.
    it: Si basa sul servizio ViaggiaTreno di Trenitalia e, per i treni Italo, su un
      endpoint non ufficiale di Italo.
Categories:
  - Public Transport
License: AGPL-3.0-or-later
AuthorName: Glauco Rampogna
SourceCode: https://github.com/rglauco/TreniRT
IssueTracker: https://github.com/rglauco/TreniRT/issues
Changelog: https://github.com/rglauco/TreniRT/blob/HEAD/CHANGELOG.md

RepoType: git
Repo: https://github.com/rglauco/TreniRT.git
Binaries: https://github.com/rglauco/TreniRT/releases/download/%v/TreniRT-%v.apk

Builds:
  - versionName: 1.7.2
    versionCode: 33
    commit: bbe61f70f3c25329ac314b6a52b5ebfad0929b6a
    subdir: android/app
    gradle:
      - yes

AllowedAPKSigningKeys: 6dc3224c91bf51b34b9b5c9c738a1aec9ba005cb58516d0fcb91b852da9f7bee

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 1.7.2
CurrentVersionCode: 33
