Categories:
  - Navigation
License: AGPL-3.0-or-later
SourceCode: https://github.com/rglauco/TreniRT
IssueTracker: https://github.com/rglauco/TreniRT/issues
Changelog: https://github.com/rglauco/TreniRT/blob/HEAD/CHANGELOG.md

RepoType: git
Repo: https://github.com/rglauco/TreniRT.git

Builds:
  - versionName: "1.5.3"
    versionCode: 10
    commit: 6195947275e87f7814c34100caf86759fe8915da
    subdir: android
    gradle:
      - yes

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: "1.5.3"
CurrentVersionCode: 10
