Categories:
  - Navigation
License: AGPL-3.0-or-later
AuthorName: Glauco Rampogna
SourceCode: https://github.com/rglauco/TreniRT
IssueTracker: https://github.com/rglauco/TreniRT/issues
Changelog: https://github.com/rglauco/TreniRT/blob/HEAD/CHANGELOG.md

RepoType: git
Repo: https://github.com/rglauco/TreniRT.git
Binaries: https://github.com/rglauco/TreniRT/releases/download/%v/TreniRT-%v.apk

Builds:
  - versionName: 1.6.5
    versionCode: 30
    commit: 4c46d2ce82fad974298482247fae0dfedecba749
    subdir: android/app
    gradle:
      - yes

AllowedAPKSigningKeys: 6dc3224c91bf51b34b9b5c9c738a1aec9ba005cb58516d0fcb91b852da9f7bee

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 1.6.5
CurrentVersionCode: 30
